2023-02-08 08:47:23,391 - db create
2023-02-08 08:47:23,506 - db create
2023-02-08 08:47:23,558 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-02-08 08:47:23,559 - Added job "222222" to job store "default"
2023-02-08 08:47:23,559 - Scheduler started
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2023-02-08 08:47:23,565 -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2023-02-08 08:47:23,566 -  * Restarting with stat
2023-02-08 08:47:23,773 - db create
2023-02-08 08:47:23,847 - db create
2023-02-08 08:47:23,893 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-02-08 08:47:23,894 - Added job "222222" to job store "default"
2023-02-08 08:47:23,894 - Scheduler started
2023-02-08 08:47:23,897 -  * Debugger is active!
2023-02-08 08:47:23,915 -  * DebuggeÂ·r PIN: 238-418-907
Traceback (most recent call last):
  File "/Users/qit/Documents/wsapp/wsapp/server/./appsrÂ·Â·v.py", line 11, in <module>
    from tqsdk import TqApi, TqAuth
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/__init__.py", line 6, in <module>
    from tqsdk.api import TqApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/api.py", line 39, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/intervaltree.pxi", line 7, in init pandas._libs.interval
  File "<frozen importlib._bootstrap>", line 398, in parent
KeyboardInterrupt
2023-02-08 08:47:35,462 - db create
2023-02-08 08:47:35,536 - db create
2023-02-08 08:47:35,584 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-02-08 08:47:35,584 - Added job "222222" to job store "default"
2023-02-08 08:47:35,584 - Scheduler started
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2023-02-08 08:47:35,589 -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2023-02-08 08:47:35,589 -  * Restarting with stat
2023-02-08 08:47:35,791 - db create
2023-02-08 08:47:35,864 - db create
2023-02-08 08:47:35,912 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-02-08 08:47:35,913 - Added job "222222" to job store "default"
2023-02-08 08:47:35,913 - Scheduler started
2023-02-08 08:47:35,916 -  * Debugger is active!
2023-02-08 08:47:35,927 -  * Debugger PIN: 238-418-907
2023-02-08 08:48:27,080 - 127.0.0.1 - - [08/Feb/2023 08:48:27] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:32,074 - 127.0.0.1 - - [08/Feb/2023 08:48:32] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:37,070 - 127.0.0.1 - - [08/Feb/2023 08:48:37] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:42,074 - 127.0.0.1 - - [08/Feb/2023 08:48:42] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:47,074 - 127.0.0.1 - - [08/Feb/2023 08:48:47] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:52,865 - 127.0.0.1 - - [08/Feb/2023 08:48:52] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:48:57,159 - 127.0.0.1 - - [08/Feb/2023 08:48:57] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:03,074 - 127.0.0.1 - - [08/Feb/2023 08:49:03] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:07,799 - 127.0.0.1 - - [08/Feb/2023 08:49:07] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:13,139 - 127.0.0.1 - - [08/Feb/2023 08:49:13] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:17,067 - 127.0.0.1 - - [08/Feb/2023 08:49:17] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:22,164 - 127.0.0.1 - - [08/Feb/2023 08:49:22] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:28,057 - 127.0.0.1 - - [08/Feb/2023 08:49:28] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:33,020 - 127.0.0.1 - - [08/Feb/2023 08:49:33] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:38,024 - 127.0.0.1 - - [08/Feb/2023 08:49:38] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:42,955 - 127.0.0.1 - - [08/Feb/2023 08:49:42] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:48,022 - 127.0.0.1 - - [08/Feb/2023 08:49:48] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:53,035 - 127.0.0.1 - - [08/Feb/2023 08:49:53] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:49:58,073 - 127.0.0.1 - - [08/Feb/2023 08:49:58] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:03,025 - 127.0.0.1 - - [08/Feb/2023 08:50:03] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:08,025 - 127.0.0.1 - - [08/Feb/2023 08:50:08] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:13,022 - 127.0.0.1 - - [08/Feb/2023 08:50:13] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:17,944 - 127.0.0.1 - - [08/Feb/2023 08:50:17] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:23,145 - 127.0.0.1 - - [08/Feb/2023 08:50:23] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:27,087 - 127.0.0.1 - - [08/Feb/2023 08:50:27] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:33,027 - 127.0.0.1 - - [08/Feb/2023 08:50:33] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:38,026 - 127.0.0.1 - - [08/Feb/2023 08:50:38] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:43,031 - 127.0.0.1 - - [08/Feb/2023 08:50:43] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:47,941 - 127.0.0.1 - - [08/Feb/2023 08:50:47] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:50:53,025 - 127.0.0.1 - - [08/Feb/2023 08:50:53] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:51:45,882 - 127.0.0.1 - - [08/Feb/2023 08:51:45] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:51:50,881 - 127.0.0.1 - - [08/Feb/2023 08:51:50] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:51:53,159 - 127.0.0.1 - - [08/Feb/2023 08:51:53] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:51:55,130 - 127.0.0.1 - - [08/Feb/2023 08:51:55] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:51:55,879 - 127.0.0.1 - - [08/Feb/2023 08:51:55] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:51:57,133 - 127.0.0.1 - - [08/Feb/2023 08:51:57] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:51:59,135 - 127.0.0.1 - - [08/Feb/2023 08:51:59] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:52:00,880 - 127.0.0.1 - - [08/Feb/2023 08:52:00] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:01,125 - 127.0.0.1 - - [08/Feb/2023 08:52:01] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:52:03,126 - 127.0.0.1 - - [08/Feb/2023 08:52:03] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:52:05,103 - 127.0.0.1 - - [08/Feb/2023 08:52:05] "[37mGET /db?name=SHFE.rb2305&scale=5 HTTP/1.1[0m" 200 -
2023-02-08 08:52:05,885 - 127.0.0.1 - - [08/Feb/2023 08:52:05] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:10,885 - 127.0.0.1 - - [08/Feb/2023 08:52:10] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:15,877 - 127.0.0.1 - - [08/Feb/2023 08:52:15] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:22,297 - 127.0.0.1 - - [08/Feb/2023 08:52:22] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:26,257 - 127.0.0.1 - - [08/Feb/2023 08:52:26] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:32,359 - 127.0.0.1 - - [08/Feb/2023 08:52:32] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:36,312 - 127.0.0.1 - - [08/Feb/2023 08:52:36] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:42,031 - 127.0.0.1 - - [08/Feb/2023 08:52:42] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:47,218 - 127.0.0.1 - - [08/Feb/2023 08:52:47] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:51,079 - 127.0.0.1 - - [08/Feb/2023 08:52:51] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:52:57,351 - 127.0.0.1 - - [08/Feb/2023 08:52:57] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:01,285 - 127.0.0.1 - - [08/Feb/2023 08:53:01] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:07,326 - 127.0.0.1 - - [08/Feb/2023 08:53:07] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:11,236 - 127.0.0.1 - - [08/Feb/2023 08:53:11] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:11,405 - 127.0.0.1 - - [08/Feb/2023 08:53:11] "[33mGET / HTTP/1.1[0m" 404 -
2023-02-08 08:53:11,442 - 127.0.0.1 - - [08/Feb/2023 08:53:11] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2023-02-08 08:53:17,369 - 127.0.0.1 - - [08/Feb/2023 08:53:17] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:20,548 - 127.0.0.1 - - [08/Feb/2023 08:53:20] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:21,258 - 127.0.0.1 - - [08/Feb/2023 08:53:21] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:27,311 - 127.0.0.1 - - [08/Feb/2023 08:53:27] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:30,759 - 127.0.0.1 - - [08/Feb/2023 08:53:30] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:31,606 - 127.0.0.1 - - [08/Feb/2023 08:53:31] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:31,942 - 127.0.0.1 - - [08/Feb/2023 08:53:31] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:32,142 - 127.0.0.1 - - [08/Feb/2023 08:53:32] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:32,156 - 127.0.0.1 - - [08/Feb/2023 08:53:32] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:32,284 - 127.0.0.1 - - [08/Feb/2023 08:53:32] "[37mGET /db HTTP/1.1[0m" 200 -
2023-02-08 08:53:38,531 - 127.0.0.1 - - [08/Feb/2023 08:53:38] "[37mGET /db HTTP/1.1[0m" 200 -
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-02-08 09:00:00,020 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:15:00 CST)" (scheduled at 2023-02-08 09:00:00+08:00)
2023-02-08 09:00:00,022 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:00:00 CST)" (scheduled at 2023-02-08 09:00:00+08:00)
2023-02-08 09:00:00,074 - sending the email
2023-02-08 09:00:00,076 - sending the email
2023-02-08 09:00:00,366 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 09:00:01,189 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 09:18:21,366 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:30:00 CST)" was missed by 0:03:21.366009
2023-02-08 09:18:21,371 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:30:00 CST)" was missed by 0:03:21.371445
2023-02-08 09:30:00,014 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:45:00 CST)" (scheduled at 2023-02-08 09:30:00+08:00)
2023-02-08 09:30:00,013 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:45:00 CST)" (scheduled at 2023-02-08 09:30:00+08:00)
2023-02-08 09:30:00,042 - sending the email
2023-02-08 09:30:00,042 - sending the email
2023-02-08 09:30:00,262 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 09:30:01,120 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 09:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 09:45:00,025 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:00:00 CST)" (scheduled at 2023-02-08 09:45:00+08:00)
2023-02-08 09:45:00,030 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:00:00 CST)" (scheduled at 2023-02-08 09:45:00+08:00)
2023-02-08 09:45:00,056 - sending the email
2023-02-08 09:45:00,056 - sending the email
2023-02-08 09:45:00,293 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 09:45:00,293 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:00:00,013 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:15:00 CST)" (scheduled at 2023-02-08 10:00:00+08:00)
2023-02-08 10:00:00,013 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:15:00 CST)" (scheduled at 2023-02-08 10:00:00+08:00)
2023-02-08 10:00:00,039 - sending the email
2023-02-08 10:00:00,039 - sending the email
2023-02-08 10:00:00,291 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:00:01,141 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:15:00,018 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:30:00 CST)" (scheduled at 2023-02-08 10:15:00+08:00)
2023-02-08 10:15:00,018 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:30:00 CST)" (scheduled at 2023-02-08 10:15:00+08:00)
2023-02-08 10:15:00,038 - sending the email
2023-02-08 10:15:00,038 - sending the email
2023-02-08 10:15:00,270 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:15:00,270 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:30:00,019 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:45:00 CST)" (scheduled at 2023-02-08 10:30:00+08:00)
2023-02-08 10:30:00,026 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:45:00 CST)" (scheduled at 2023-02-08 10:30:00+08:00)
2023-02-08 10:30:00,052 - sending the email
2023-02-08 10:30:00,052 - sending the email
2023-02-08 10:30:00,348 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:30:01,146 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 10:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:45:00,024 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:00:00 CST)" (scheduled at 2023-02-08 10:45:00+08:00)
2023-02-08 10:45:00,026 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:00:00 CST)" (scheduled at 2023-02-08 10:45:00+08:00)
2023-02-08 10:45:00,146 - sending the email
2023-02-08 10:45:00,160 - sending the email
2023-02-08 10:45:00,384 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 10:45:00,384 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:00:00,024 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:15:00 CST)" (scheduled at 2023-02-08 11:00:00+08:00)
2023-02-08 11:00:00,033 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:15:00 CST)" (scheduled at 2023-02-08 11:00:00+08:00)
2023-02-08 11:00:00,063 - sending the email
2023-02-08 11:00:00,063 - sending the email
2023-02-08 11:00:00,412 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:00:01,150 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:15:00,038 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:30:00 CST)" (scheduled at 2023-02-08 11:15:00+08:00)
2023-02-08 11:15:00,037 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:30:00 CST)" (scheduled at 2023-02-08 11:15:00+08:00)
2023-02-08 11:15:00,062 - sending the email
2023-02-08 11:15:00,062 - sending the email
2023-02-08 11:15:00,355 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:15:00,355 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:30:00,015 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:45:00 CST)" (scheduled at 2023-02-08 11:30:00+08:00)
2023-02-08 11:30:00,019 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:45:00 CST)" (scheduled at 2023-02-08 11:30:00+08:00)
2023-02-08 11:30:00,043 - sending the email
2023-02-08 11:30:00,043 - sending the email
2023-02-08 11:30:00,309 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:30:01,211 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 11:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:45:00,013 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:00:00 CST)" (scheduled at 2023-02-08 11:45:00+08:00)
2023-02-08 11:45:00,013 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:00:00 CST)" (scheduled at 2023-02-08 11:45:00+08:00)
2023-02-08 11:45:00,033 - sending the email
2023-02-08 11:45:00,033 - sending the email
2023-02-08 11:45:00,306 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 11:45:00,308 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:00:00,020 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:15:00 CST)" (scheduled at 2023-02-08 12:00:00+08:00)
2023-02-08 12:00:00,027 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:15:00 CST)" (scheduled at 2023-02-08 12:00:00+08:00)
2023-02-08 12:00:00,049 - sending the email
2023-02-08 12:00:00,049 - sending the email
2023-02-08 12:00:00,391 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:00:01,130 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:15:00,040 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:30:00 CST)" (scheduled at 2023-02-08 12:15:00+08:00)
2023-02-08 12:15:00,045 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:30:00 CST)" (scheduled at 2023-02-08 12:15:00+08:00)
2023-02-08 12:15:00,060 - sending the email
2023-02-08 12:15:00,060 - sending the email
2023-02-08 12:15:00,280 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:15:00,282 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:30:00,038 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:45:00 CST)" (scheduled at 2023-02-08 12:30:00+08:00)
2023-02-08 12:30:00,044 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:45:00 CST)" (scheduled at 2023-02-08 12:30:00+08:00)
2023-02-08 12:30:00,076 - sending the email
2023-02-08 12:30:00,076 - sending the email
2023-02-08 12:30:00,326 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:30:01,152 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 12:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:45:00,016 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:00:00 CST)" (scheduled at 2023-02-08 12:45:00+08:00)
2023-02-08 12:45:00,017 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:00:00 CST)" (scheduled at 2023-02-08 12:45:00+08:00)
2023-02-08 12:45:00,054 - sending the email
2023-02-08 12:45:00,054 - sending the email
2023-02-08 12:45:00,197 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 12:45:00,197 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:00:00,022 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:15:00 CST)" (scheduled at 2023-02-08 13:00:00+08:00)
2023-02-08 13:00:00,028 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:15:00 CST)" (scheduled at 2023-02-08 13:00:00+08:00)
2023-02-08 13:00:00,065 - sending the email
2023-02-08 13:00:00,065 - sending the email
2023-02-08 13:00:00,164 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:00:01,251 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:15:00,018 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:30:00 CST)" (scheduled at 2023-02-08 13:15:00+08:00)
2023-02-08 13:15:00,021 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:30:00 CST)" (scheduled at 2023-02-08 13:15:00+08:00)
2023-02-08 13:15:00,045 - sending the email
2023-02-08 13:15:00,045 - sending the email
2023-02-08 13:15:00,315 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:15:00,317 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:30:00,032 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:45:00 CST)" (scheduled at 2023-02-08 13:30:00+08:00)
2023-02-08 13:30:00,035 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:45:00 CST)" (scheduled at 2023-02-08 13:30:00+08:00)
2023-02-08 13:30:00,156 - sending the email
2023-02-08 13:30:00,156 - sending the email
2023-02-08 13:30:00,232 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:30:01,235 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 13:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:45:00,016 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:00:00 CST)" (scheduled at 2023-02-08 13:45:00+08:00)
2023-02-08 13:45:00,025 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:00:00 CST)" (scheduled at 2023-02-08 13:45:00+08:00)
2023-02-08 13:45:00,058 - sending the email
2023-02-08 13:45:00,058 - sending the email
2023-02-08 13:45:00,337 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 13:45:00,339 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:00:00,020 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:15:00 CST)" (scheduled at 2023-02-08 14:00:00+08:00)
2023-02-08 14:00:00,028 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:15:00 CST)" (scheduled at 2023-02-08 14:00:00+08:00)
2023-02-08 14:00:00,056 - sending the email
2023-02-08 14:00:00,056 - sending the email
2023-02-08 14:00:00,294 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:00:01,168 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:15:00,021 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:30:00 CST)" (scheduled at 2023-02-08 14:15:00+08:00)
2023-02-08 14:15:00,019 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:30:00 CST)" (scheduled at 2023-02-08 14:15:00+08:00)
2023-02-08 14:15:00,040 - sending the email
2023-02-08 14:15:00,040 - sending the email
2023-02-08 14:15:00,280 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:15:00,280 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:30:00,018 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:45:00 CST)" (scheduled at 2023-02-08 14:30:00+08:00)
2023-02-08 14:30:00,017 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:45:00 CST)" (scheduled at 2023-02-08 14:30:00+08:00)
2023-02-08 14:30:00,046 - sending the email
2023-02-08 14:30:00,046 - sending the email
2023-02-08 14:30:00,288 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:30:01,124 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 14:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:45:00,014 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:00:00 CST)" (scheduled at 2023-02-08 14:45:00+08:00)
2023-02-08 14:45:00,014 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:00:00 CST)" (scheduled at 2023-02-08 14:45:00+08:00)
2023-02-08 14:45:00,036 - sending the email
2023-02-08 14:45:00,036 - sending the email
2023-02-08 14:45:00,108 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 14:45:00,111 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:00:00,008 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:15:00 CST)" (scheduled at 2023-02-08 15:00:00+08:00)
2023-02-08 15:00:00,010 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:15:00 CST)" (scheduled at 2023-02-08 15:00:00+08:00)
2023-02-08 15:00:00,043 - sending the email
2023-02-08 15:00:00,043 - sending the email
2023-02-08 15:00:00,259 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:00:01,119 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:15:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:15:00,014 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:30:00 CST)" (scheduled at 2023-02-08 15:15:00+08:00)
2023-02-08 15:15:00,014 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:30:00 CST)" (scheduled at 2023-02-08 15:15:00+08:00)
2023-02-08 15:15:00,037 - sending the email
2023-02-08 15:15:00,037 - sending the email
2023-02-08 15:15:00,341 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:15:00,342 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:30:00,010 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:45:00 CST)" (scheduled at 2023-02-08 15:30:00+08:00)
2023-02-08 15:30:00,010 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:45:00 CST)" (scheduled at 2023-02-08 15:30:00+08:00)
2023-02-08 15:30:00,039 - sending the email
2023-02-08 15:30:00,039 - sending the email
2023-02-08 15:30:00,307 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:30:01,211 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-08 15:45:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:45:00,016 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-09 09:00:00 CST)" (scheduled at 2023-02-08 15:45:00+08:00)
2023-02-08 15:45:00,017 - Running job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-09 09:00:00 CST)" (scheduled at 2023-02-08 15:45:00+08:00)
2023-02-08 15:45:00,034 - sending the email
2023-02-08 15:45:00,034 - sending the email
2023-02-08 15:45:00,135 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-09 09:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/./app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-08 15:45:00,147 - Job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-09 09:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/qit/Documents/wsapp/wsapp/server/app.py", line 251, in email_futures_big_records
    Email.send_email(content)
  File "/Users/qit/Documents/wsapp/wsapp/server/util/email.py", line 22, in send_email
    smtpServer.login(sender, sys.argv[1])
IndexError: list index out of range
2023-02-09 19:55:57,541 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-10 09:00:00 CST)" was missed by 4:10:57.540955
2023-02-09 19:55:57,544 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-10 09:00:00 CST)" was missed by 4:10:57.544811
2023-02-10 18:02:58,662 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-13 09:00:00 CST)" was missed by 2:17:58.662745
2023-02-10 18:02:58,662 - Run time of job "222222 (trigger: cron[day_of_week='mon-fri', hour='9-15', minute='*/15'], next run at: 2023-02-13 09:00:00 CST)" was missed by 2:17:58.662907
2023-06-01 21:48:14,246 - db create
2023-06-01 21:48:14,366 - db create
2023-06-01 21:48:14,417 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-06-01 21:48:14,418 - Added job "222222" to job store "default"
2023-06-01 21:48:14,418 - Scheduler started
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2023-06-01 21:48:14,425 -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2023-06-01 21:48:14,425 -  * Restarting with stat
2023-06-01 21:48:14,631 - db create
2023-06-01 21:48:14,708 - db create
2023-06-01 21:48:14,756 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-06-01 21:48:14,757 - Added job "222222" to job store "default"
2023-06-01 21:48:14,757 - Scheduler started
2023-06-01 21:48:14,760 -  * Debugger is active!
2023-06-01 21:48:14,778 -  * Debugger PIN: 238-418-907
2023-06-01 21:48:15,557 - 127.0.0.1 - - [01/Jun/2023 21:48:15] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:20,554 - 127.0.0.1 - - [01/Jun/2023 21:48:20] "[37mGET /db HTTP/1.1[0m" 200 -
Traceback (most recent call last):
  File "/Users/qit/Documents/wsapp/wsapp/server/./appsrv.py", line 11, in <module>
    from tqsdk import TqApi, TqAuth
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/__init__.py", line 6, in <module>
    from tqsdk.api import TqApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/api.py", line 72, in <module>
    from tqsdk.tqwebhelper import TqWebHelper
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/tqwebhelper.py", line 14, in <module>
    from aiohttp import web
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/web.py", line 24, in <module>
    from .web_app import Application as Application, CleanupError as CleanupError
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/web_app.py", line 40, in <module>
    from .web_middlewares import _fix_request_current_app
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 8, in <module>
    from .web_urldispatcher import SystemRoute
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 53, in <module>
    from .web_routedef import AbstractRouteDef
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/web_routedef.py", line 59, in <module>
    class RouteDef(AbstractRouteDef):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/attr/_make.py", line 1525, in wrap
    builder = _ClassBuilder(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/attr/_make.py", line 704, in __init__
    self._cls_dict = dict(cls.__dict__) if slots else {}
KeyboardInterrupt
2023-06-01 21:48:25,024 - db create
2023-06-01 21:48:25,106 - db create
2023-06-01 21:48:25,153 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-06-01 21:48:25,154 - Added job "222222" to job store "default"
2023-06-01 21:48:25,154 - Scheduler started
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2023-06-01 21:48:25,158 -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
2023-06-01 21:48:25,159 -  * Restarting with stat
2023-06-01 21:48:25,370 - db create
2023-06-01 21:48:25,449 - db create
2023-06-01 21:48:25,496 - Adding job tentatively -- it will be properly scheduled when the scheduler starts
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
2023-06-01 21:48:25,497 - Added job "222222" to job store "default"
2023-06-01 21:48:25,497 - Scheduler started
2023-06-01 21:48:25,500 -  * Debugger is active!
2023-06-01 21:48:25,512 -  * Debugger PIN: 238-418-907
2023-06-01 21:48:25,552 - 127.0.0.1 - - [01/Jun/2023 21:48:25] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:30,560 - 127.0.0.1 - - [01/Jun/2023 21:48:30] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:35,550 - 127.0.0.1 - - [01/Jun/2023 21:48:35] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:40,555 - 127.0.0.1 - - [01/Jun/2023 21:48:40] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:45,552 - 127.0.0.1 - - [01/Jun/2023 21:48:45] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:50,558 - 127.0.0.1 - - [01/Jun/2023 21:48:50] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:48:55,548 - 127.0.0.1 - - [01/Jun/2023 21:48:55] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:00,562 - 127.0.0.1 - - [01/Jun/2023 21:49:00] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:05,567 - 127.0.0.1 - - [01/Jun/2023 21:49:05] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:10,569 - 127.0.0.1 - - [01/Jun/2023 21:49:10] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:15,563 - 127.0.0.1 - - [01/Jun/2023 21:49:15] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:20,555 - 127.0.0.1 - - [01/Jun/2023 21:49:20] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:25,563 - 127.0.0.1 - - [01/Jun/2023 21:49:25] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:30,561 - 127.0.0.1 - - [01/Jun/2023 21:49:30] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:35,558 - 127.0.0.1 - - [01/Jun/2023 21:49:35] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:40,562 - 127.0.0.1 - - [01/Jun/2023 21:49:40] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:45,564 - 127.0.0.1 - - [01/Jun/2023 21:49:45] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:50,557 - 127.0.0.1 - - [01/Jun/2023 21:49:50] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:49:55,563 - 127.0.0.1 - - [01/Jun/2023 21:49:55] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:00,564 - 127.0.0.1 - - [01/Jun/2023 21:50:00] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:05,561 - 127.0.0.1 - - [01/Jun/2023 21:50:05] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:10,560 - 127.0.0.1 - - [01/Jun/2023 21:50:10] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:15,558 - 127.0.0.1 - - [01/Jun/2023 21:50:15] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:20,563 - 127.0.0.1 - - [01/Jun/2023 21:50:20] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:25,560 - 127.0.0.1 - - [01/Jun/2023 21:50:25] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:30,557 - 127.0.0.1 - - [01/Jun/2023 21:50:30] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:35,564 - 127.0.0.1 - - [01/Jun/2023 21:50:35] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:40,562 - 127.0.0.1 - - [01/Jun/2023 21:50:40] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:45,564 - 127.0.0.1 - - [01/Jun/2023 21:50:45] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:50,560 - 127.0.0.1 - - [01/Jun/2023 21:50:50] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:50:55,567 - 127.0.0.1 - - [01/Jun/2023 21:50:55] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:51:00,562 - 127.0.0.1 - - [01/Jun/2023 21:51:00] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:51:05,557 - 127.0.0.1 - - [01/Jun/2023 21:51:05] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:51:10,558 - 127.0.0.1 - - [01/Jun/2023 21:51:10] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:51:15,562 - 127.0.0.1 - - [01/Jun/2023 21:51:15] "[37mGET /db HTTP/1.1[0m" 200 -
2023-06-01 21:51:20,560 - 127.0.0.1 - - [01/Jun/2023 21:51:20] "[37mGET /db HTTP/1.1[0m" 200 -
Traceback (most recent call last):
  File "/Users/qit/Documents/wsapp/wsapp/server/./appsrv.py", line 11, in <module>
    from tqsdk import TqApi, TqAuth
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/__init__.py", line 6, in <module>
    from tqsdk.api import TqApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/api.py", line 50, in <module>
    from tqsdk.multiaccount import TqMultiAccount
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/multiaccount.py", line 12, in <module>
    from tqsdk.tradeable import TqAccount, TqKq, TqKqStock, TqSim, TqSimStock, BaseSim, BaseOtg
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/tradeable/__init__.py", line 9, in <module>
    from tqsdk.tradeable.sim.basesim import BaseSim
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/tradeable/sim/__init__.py", line 6, in <module>
    from tqsdk.tradeable.sim.tqsim import TqSim
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/tradeable/sim/tqsim.py", line 10, in <module>
    from tqsdk.report import TqReport
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/report.py", line 11, in <module>
    from tqsdk.tafunc import get_sharp, get_sortino, get_calmar, _cum_counts
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tqsdk/tafunc.py", line 18, in <module>
    from scipy import stats
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scipy/stats/__init__.py", line 456, in <module>
    from ._morestats import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scipy/stats/_morestats.py", line 14, in <module>
    from . import _statlib
KeyboardInterrupt
